spring.application.name=LojaVeiculo

# Banco H2 configuracao
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=4A7D5E3C9B1F8A2E6D4C7F9A5B8E1D3C6F2A9B7E5D1C4F8A6B3E9D2C7F5A1E8
jwt.expiration=3600000

# Api de cambio do Dolar para Real

frankfurter.url=https://api.frankfurter.dev/v1/latest?from=USD&to=BRL
